const char* masterStyleSheet = 
"@import url('https://dev-cats.github.io/code-snippets/JetBrainsMono.css');\n"
"* {\n"
"	font-family: 'Jetbrains Mono';\n"
"}\n"
"\n"
":root {\n"
"	--hue: 200;\n"
"	--bg-sat: 10%;\n"
"	--bg-lit: 10%;\n"
"\n"
"	--txt-sat: 80%;\n"
"	--txt-lit: 50%;\n"
"\n"
"	--subsect-hue: 100;\n"
"	--function-hue: 50;\n"
"	--opcode-hue: 350;\n"
"	--prefix-hue: 300;\n"
"	--immediate-hue: 25;\n"
"	--operrand-hue-base: 100;\n"
"	--operrand1-hue: calc(var(--operrand-hue-base) + 0);\n"
"	--operrand2-hue: calc(var(--operrand-hue-base) + 50);\n"
"	--operrand3-hue: calc(var(--operrand-hue-base) + 100);\n"
"}\n"
"\n"
"* {\n"
"	color: hsl(var(--hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
"\n"
"body {\n"
"	background: hsl(var(--hue),var(--bg-sat),var(--bg-lit));\n"
"}\n"
"\n"
".FunctionName {\n"
"	color: hsl(var(--function-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".SubSectionName {\n"
"	color: hsl(var(--subsect-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
"\n"
".failed {\n"
"	color: red;\n"
"}\n"
"\n"
".HexDisplay {\n"
"	color: hsl(var(--immediate-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
"\n"
"/*\n"
"	. encoded\n"
"*/\n"
".encoded {\n"
"	font-size: 16px;\n"
"}\n"
".encoded.byte {\n"
"	padding-right: 5px;\n"
"}\n"
"\n"
"/*\n"
"	. decoded\n"
"*/\n"
".InstructionComponent {\n"
"	padding-right: 15px;\n"
"}\n"
".decoded {\n"
"	font-size: 16px;\n"
"}\n"
".decoded span {\n"
"	padding-left: 5px;\n"
"}\n"
"\n"
"/*\n"
"	. encoded & decoded\n"
"*/\n"
".opcode {\n"
"	color: hsl(var(--opcode-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".prefix {\n"
"	color: hsl(var(--prefix-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".operrand1 {\n"
"	color: hsl(var(--operrand1-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".operrand2 {\n"
"	color: hsl(var(--operrand2-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".operrand3 {\n"
"	color: hsl(var(--operrand3-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
;