const char* masterStyleSheet = 
"@import url('https://dev-cats.github.io/code-snippets/JetBrainsMono.css');\n"
"* {\n"
"	font-family: 'Jetbrains Mono';\n"
"}\n"
"\n"
":root {\n"
"	--hue: 200;\n"
"	--bg-sat: 10%;\n"
"	--bg-lit: 10%;\n"
"\n"
"	--txt-sat: 80%;\n"
"	--txt-lit: 50%;\n"
"\n"
"	--opcode-hue: 350;\n"
"	--prefix-hue: 300;\n"
"	--operrand-hue-base: 100;\n"
"	--operrand1-hue: calc(var(--operrand-hue-base) + 0);\n"
"	--operrand2-hue: calc(var(--operrand-hue-base) + 50);\n"
"	--operrand3-hue: calc(var(--operrand-hue-base) + 100);\n"
"}\n"
"\n"
"* {\n"
"	color: hsl(var(--hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
"\n"
"body {\n"
"	background: hsl(var(--hue),var(--bg-sat),var(--bg-lit));\n"
"}\n"
"\n"
".instruction {\n"
"	background: hsl(var(--hue),var(--bg-sat),calc(var(--bg-lit) + 10%));\n"
"	border-radius: 8px;\n"
"	padding: 10px;\n"
"	margin-bottom: 10px;\n"
"}\n"
"\n"
".HexDisplay {\n"
"	color: inherit;\n"
"}\n"
"\n"
"/*\n"
"	. encoded\n"
"*/\n"
".encoded {\n"
"	font-size: 14px;\n"
"}\n"
".encoded .byte {\n"
"	padding-left: 5px;\n"
"	color: inherit;\n"
"}\n"
"\n"
"/*\n"
"	. decoded\n"
"*/\n"
".decoded {\n"
"	font-size: 20px;\n"
"}\n"
".decoded span {\n"
"	padding-left: 5px;\n"
"}\n"
"\n"
"/*\n"
"	. encoded & decoded\n"
"*/\n"
".opcode {\n"
"	color: hsl(var(--opcode-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".prefix {\n"
"	color: hsl(var(--prefix-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".operrand1 {\n"
"	color: hsl(var(--operrand1-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".operrand2 {\n"
"	color: hsl(var(--operrand2-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
".operrand3 {\n"
"	color: hsl(var(--operrand3-hue),var(--txt-sat),var(--txt-lit));\n"
"}\n"
;